### ISSUE TITLE
Pool Card - Display tokens deposited in our pools

### ISSUE THREAD

**Issue by redDwarf03** [archethic-foundation/dex#134]
### Describe the solution you'd like

From @Rudy-Perrin
Would it be possible to display the details of the tokens deposited in our pools? There we only have the number of LPs. And we can't know how much it brought us?

**Comment by Rudy-Perrin** [comment]
Thank you !
I find it more reassuring and practical to know how much I deposited.

Would it be possible to add a link (on the "Equivalent..." line) which opens a page or a popup to list all the transactions (deposits/withdrawals) that have been made to this pool with the links to aeExplorer?

**Comment by redDwarf03** [comment]
hello @Rudy-Perrin 
i created an issue https://github.com/archethic-foundation/dex/issues/176
