### ISSUE TITLE
transaction bridge

### ISSUE THREAD

**Issue by luciobaranelli** [archethic-foundation/dex#289]
### Describe the problem you discovered

Bonjour, j'ai voulu transférer mes uco de mon compte metamask vers mon wallet archethic, comme j'ai deja fait par le passé, mais cela ne fonctionne pas. Je suis passé par le brigde, j'ai validé les approbations et le transfert, tout était ok et à la derniere étape j'ai le message de fond insuffisant, alors que j'en ai. Or sur etherscan ma transaction est bien effective avec les frais de gaz qui vont avec, mais plus d'UCO sur mon méta et pas d'UCO on plus sur mon wallet archethic. Ou sont il ?
numéro du bug sur la fin du transfert : 0x5e7d03a24e9963c8da69a74d40d6b9e7bc34e8a3     avec mes 8691 UCO que j'ai transféré.
numéro de la transaction sur etherscan : 0x6a70d8bedd92c1f3258f187e54a0c22aceeda24ce604088b7a8b43e65e1cd0a0.

Merci de bien vouloir m'aiguiller sur les éventuelles démarches à faire pour le remboursement ou autres.

**Comment by Krikor-tech** [comment]
@luciobaranelli Thanks for posting the issue.

Your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support : [Help Center](https://allchainrectification.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by redDwarf03** [comment]
Issue transfered to Archethic support

**Comment by luciobaranelli** [comment]
Bonjour,
Merci pour la manipulation, j'attendais que les frais de gas baissent.
Ce matin j'ai fait le remboursement, cela à marcher normalement. Ensuite j'ai refait la manip pour enfin pouvoir mettre en earn mes UCO ET REBELOTTE, ca coince au moment du bridge.................................. Là ca commence a faire chère en frais de GAS !!!!!
Suis-je le seul à avoir des problemes sur le bridge ?

**Comment by redDwarf03** [comment]
Bonjour.
Nous n’avons pas de remontées d’erreurs spécifiques en ce moment.
Quel wallet EVM utilisez vous?

**Comment by redDwarf03** [comment]
Autre question, avez vous des uco sur votre wallet Archethic pour payer les frais de transaction du bridge?

**Comment by redDwarf03** [comment]
À noter que vous avez 2h entre le moment de votre bridge et la possibilité de reprendre le traitement là où il s’est arrêté. En allant dans le menu any troubles puis access au local history puis bouton resume

**Comment by luciobaranelli** [comment]
J'ai passer mes UCO V1 en V2 ce matin.
Ensuite mes UCO sont sur mon compte métamask que je veux renvoyer sur le Archethic wallet, j'ai l'extension sur mon navigateur chrome

**Comment by luciobaranelli** [comment]
J'avais des UCO que j'ai converti en AEeth y a deja un bon moment

**Comment by redDwarf03** [comment]
Quelle est la balance exacte de uco actuellement sur votre wallet Archethic?

**Comment by luciobaranelli** [comment]
0.21714837 UCO

**Comment by redDwarf03** [comment]
Ok c’est ça le pb. Vous n’avez pas assez de uco pour finir votre bridge.
Je vous recommande donc de créer dans votre wallet Archethic un nouveau compte. Ensuite vous Bridgez sur ce compte à 0 car quand un compte est à 0, Archethic offre les frais de bridge pour la partie uco

**Comment by luciobaranelli** [comment]
Ok merci de l'astuce je vais essayer ca et tiens au jus

**Comment by luciobaranelli** [comment]
Re, j'ai bien recréer un compte mais je n,'arrive pas a le selectionner sur l'extention et sur le Tel le bridge n'est pas possible

**Comment by luciobaranelli** [comment]
Bjr,
Merci j'ai enfin pu faire le bridge, ca aura mis le temps mais c'est good.
Merci encore pour tes reponses. Bonne continuation
